### ISSUE TITLE
Migration tool is not working

### ISSUE THREAD

**Issue by vbulbul** [chirpstack/chirpstack-v3-to-v4#6]
```
./chirpstack-v3-to-v4 --as-config-file /etc/chirpstack-application-server/chirpstack-application-server.toml --ns-config-file /etc/chirpstack-network-server/chirpstack-network-server.toml --cs-config-file /etc/chirpstack/chirpstack.toml
2022/10/10 16:15:30 Reading ChirpStack configuration file: /etc/chirpstack/chirpstack.toml
2022/10/10 16:15:30 Reading AS configuration file: /etc/chirpstack-application-server/chirpstack-application-server.toml
2022/10/10 16:15:30 Deleting users and tenants from target database
2022/10/10 16:15:30 Migrating users
2022/10/10 16:15:30 Migrating organizations
2022/10/10 16:15:30 Migrating organization users
2022/10/10 16:15:30 Migrating applications
2022/10/10 16:15:30 Reading NS configuration file: /etc/chirpstack-network-server/chirpstack-network-server.toml
2022/10/10 16:15:30 Migrating gateways
2022/10/10 16:15:30 Migrating device-profiles
panic: sql: no rows in result set

goroutine 1 [running]:
main.migrateDeviceProfiles()
        /chirpstack-v3-to-v4/main.go:549 +0x7cc
main.run(0xa6a4b0, {0x1d24540, 0x0, 0x6})
        /chirpstack-v3-to-v4/main.go:113 +0x37c
github.com/spf13/cobra.(*Command).execute(0xa6a4b0, {0x1d020c8, 0x6, 0x7})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x6b0
github.com/spf13/cobra.(*Command).ExecuteC(0xa6a4b0)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x414
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /chirpstack-v3-to-v4/main.go:79 +0x20
```

**Comment by hoffi085** [comment]
Hi,
I got follwing error when migrating:
~~~
2022/10/13 09:38:01 Reading ChirpStack configuration file: /etc/chirpstack/chirpstack.toml
2022/10/13 09:38:01 Reading AS configuration file: /etc/chirpstack-application-server/chirpstack-application-server.toml
2022/10/13 09:38:01 Deleting users and tenants from target database
2022/10/13 09:38:02 Migrating users
2022/10/13 09:38:02 Migrating organizations
2022/10/13 09:38:02 Migrating organization users
2022/10/13 09:38:02 Migrating applications
2022/10/13 09:38:02 Migrating application integrations
2022/10/13 09:38:02 Reading NS configuration file: /etc/chirpstack-network-server/chirpstack-network-server.toml
2022/10/13 09:38:02 Migrating gateways
redis: 2022/10/13 09:38:02 sentinel.go:700: sentinel: discovered new sentinel="redis-node-0.redis-headless.default.svc.cluster.local:26379" for master="mymaster"
redis: 2022/10/13 09:38:02 sentinel.go:700: sentinel: discovered new sentinel="redis-node-2.redis-headless.default.svc.cluster.local:26379" for master="mymaster"
redis: 2022/10/13 09:38:02 sentinel.go:661: sentinel: new master="mymaster" addr="redis-node-2.redis-headless.default.svc.cluster.local:6379"
2022/10/13 09:38:02 Migrate gateway metrics error: dial tcp: lookup $REDIS_HOST: no such host
panic: dial tcp: lookup $REDIS_HOST: no such host

goroutine 1 [running]:
main.migrateGatewayMetrics({0xc0001c1a70, 0x8, 0xc0000a8000?})
        /chirpstack-v3-to-v4/main.go:1548 +0x725
main.migrateGateways()
        /chirpstack-v3-to-v4/main.go:889 +0x5a7
main.run(0xf32a20?, {0xa9ad67?, 0x6?, 0x6?})
        /chirpstack-v3-to-v4/main.go:113 +0x575
github.com/spf13/cobra.(*Command).execute(0xf32a20, {0xc0000ba010, 0x6, 0x6})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xf32a20)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /chirpstack-v3-to-v4/main.go:79 +0x25
~~~

I've confirmed that the environment variable $REDIS_HOST exists, so that should not be the problem. As I'm using Redis in sentinel mode, I think that could be the problem, but there is no configuration in chirpstack.toml (v4) like it was in chirpstack v3.

**Comment by brocaar** [comment]
@hoffi085 

Sorry if this wasn't clear. The env-variable parsing is a feature of ChirpStack v4, it is not implemented in the migration script. You should replace it with the real value. ChirpStack v4 currently does not provide Sentinel support, as it is not provided by the Rust Redis client.

@vbulbul 

It looks like your databases are out of sync. The device-profile exists in one database, but not the other.

**Comment by mvniekerk** [comment]
Hi @brocaar 
I've got a similar issue but instead of Redis it is complaining about `panic: dial tcp: lookup $POSTGRESQL_HOST: no such host`

Where does one set these parameters then?

**Comment by mvniekerk** [comment]
Kindly ignore the above comment. I've nuked my Postgres in anyway. 
Muscle memory of adding the -v to docker-compose down. (Pop goes the prod data)

**Comment by brocaar** [comment]
This tool does not support the environment variable feature in config files. I will update the README.md.

**Comment by GrayCygnus** [comment]
@brocaar hey there, just to clarify and perhaps resolve the issue I posted. Does this mean that:

If we want to use the migration tool, all env variables in our ns.toml, as.toml, and cs.toml files should be replaced with the "real value"? 

Because the migration tool does not support them (that tool does not go and parse what are the envs and proceed) but chirpstack per se does use them.

Is this summary correct?

**Comment by brocaar** [comment]
Yes, that is correct. This feature is not supported by the migration tool but is indeed supported by ChirpStack v4.
